server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-sbgb}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      login-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    doc-expansion: none
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,loggers,env,threaddump,heapdump,scheduledtasks
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true
  info:
    env:
      enabled: true
    git:
      mode: full

spring.boot.admin:
  context-path: /admin
  client:
    url: http://localhost:${server.port}/admin
    instance:
      service-base-url: http://localhost:${server.port}
info:
  app:
    name: SpaceBackGroundBuilder
    version: "@project.version@"