version: '3.8'

services:
  db_sbgb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB:-db-sbgb}
    ports:
      - 5432:5432
    volumes:
      - db_sbgb-data:/var/lib/postgresql/data

volumes:
  db_sbgb-data: