apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sbgb-ingress
  namespace: sbgb
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - bree
      secretName: sbgb-tls-secret
  rules:
    - host: bree
      http:
        paths:
          - path: /sbgb/
            pathType: Prefix
            backend:
              service:
                name: sbgb-frontend
                port:
                  number: 80
