{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sbgb.fullname" . }}
  labels:
    {{- include "sbgb.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.basePath }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "sbgb.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.servicePort }}
          - path: {{ .Values.ingress.basePath }}/api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "sbgb.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.servicePort }}
{{- end }}
